# Generated by Django 4.2.3 on 2023-07-27 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ch_product',
            name='image',
            field=models.ImageField(upload_to='Cho_card/img'),
        ),
    ]
