# Generated by Django 4.2.3 on 2023-07-27 05:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_ch_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='ch_product',
            name='last',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ch_product',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ch_product',
            name='price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
