# Generated by Django 4.2.3 on 2023-07-27 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_ch_product_last_ch_product_name_ch_product_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ch_Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='Slider/img')),
                ('decoration', models.TextField(max_length=500)),
            ],
        ),
    ]
