# Generated by Django 4.2 on 2023-04-19 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_carousel'),
    ]

    operations = [
        migrations.AddField(
            model_name='carousel',
            name='Decoration',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
    ]
