# Generated by Django 4.2 on 2023-05-17 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='Email',
            field=models.EmailField(max_length=50),
        ),
    ]
