# Generated by Django 4.2 on 2023-05-18 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_order_date_order_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='date',
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='image',
            field=models.ImageField(upload_to='media/order'),
        ),
    ]
