# Generated by Django 4.2 on 2023-05-18 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_alter_order_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='date',
        ),
    ]
