# Generated by Django 4.2 on 2023-05-19 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0015_order_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='date',
        ),
    ]
