# Generated by Django 4.2 on 2023-05-19 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0016_remove_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='Product',
            field=models.CharField(max_length=40),
        ),
    ]
