# Generated by Django 4.2.1 on 2023-05-05 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('Date', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('moblie', models.IntegerField()),
                ('gender', models.GenericIPAddressField()),
                ('occupation', models.CharField(max_length=50)),
                ('ID_type', models.CharField(max_length=50)),
                ('ID_number', models.IntegerField()),
                ('Issue_Authority', models.CharField(max_length=50)),
                ('Issue_Date', models.DateField()),
                ('Issue_State', models.CharField(max_length=50)),
                ('Expliry_Date', models.DateField()),
            ],
        ),
    ]
