# Generated by Django 4.2 on 2023-04-21 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_form_oxdu_select'),
    ]

    operations = [
        migrations.RenameField(
            model_name='form_oxdu',
            old_name='name',
            new_name='nam',
        ),
    ]
