# Generated by Django 4.2 on 2023-04-21 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_rename_name_form_oxdu_nam'),
    ]

    operations = [
        migrations.RenameField(
            model_name='form_oxdu',
            old_name='nam',
            new_name='name',
        ),
    ]
